version: '3.9'
services:
  portainer:
    container_name: portainer
    image: 'docker.io/portainer/portainer-ce'
#    ports:
#      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
    labels:
      org.label-schema.group: 'portainer'

volumes:
  portainer-data:
    driver: local